spring.application.name=b1

spring.datasoure.url=jdbc:h2:men:testdb
spring.datasourt.driverClassName = org.h2.Driver
spring.datasourt.username = sa
spring.datasourt.password =

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true


spring.h2.console.enabled = true
spring.h2.console.path = /h2-console